version: '3'

services:
  db:
    image: postgres:17.0
    container_name: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: green-energy
    volumes:
      - ./dataset:/docker-entrypoint-initdb.d