version: '3'

services:
  db:
    image: postgres:17.0
    container_name: postgres
    ports:
      - '${DB_PORT}:5432'
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    restart: always
    
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: charging-station-app
    ports:
      - '${APP_PORT}:3000'
    volumes:
      - ./src:/app/src
    depends_on:
      - db

    restart: always
